(require 'auto-complete-config)
(electric-indent-mode 0)
(global-linum-mode 1)
(setq linum-format "%4d \u2502")
(global-subword-mode 1)
(setq search-highlight t)
(transient-mark-mode)
(set-default-font "Courier New-13")
(autopair-global-mode 1)
(setq ac-delay 0.0)
(setq ac-quick-help-delay 0.5)
(ac-config-default)
(add-hook 'prog-mode-hook #'rainbow-delimiters-mode)
(load-theme 'noctilux t)
(setq frame-title-format "emacs")
(menu-bar-mode -1)
(tool-bar-mode -1)
(scroll-bar-mode -1)
(set-default 'cursor-type 'hbar)
(column-number-mode 1)
(ido-mode 1)
(line-number-mode 1)
(show-paren-mode 1)
(global-hl-line-mode 1)
(winner-mode t)
(display-time)
(windmove-default-keybindings)
(global-undo-tree-mode)
(powerline-center-theme)
(setq powerline-default-separator 'wave)

(setq x-select-enable-clipboard t
      x-select-enable-primary t)
